import type { Candidate,  ElectionState } from './types';

export const CANDIDATES: Candidate[] = [
  // King
  {
    id: 'king-1',
    name: 'Emmanuel Asante',
    nickname: 'Manny',
    department: 'Mechanical Engineering',
    year: 'Level 400',
    category: 'king',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop&auto=format',
    bio: 'Student council president who has championed welfare improvements for MTU students for two years running.',
    talent: 'Public Speaking & Leadership',
    isActive: true,
  },
  {
    id: 'king-2',
    name: 'Kwame Boateng',
    nickname: 'KB',
    department: 'Computer Science',
    year: 'Level 300',
    category: 'king',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=500&fit=crop&auto=format',
    bio: 'Award-winning hackathon champion who founded the MTU Tech Club, mentoring 200+ students across campus.',
    talent: 'Software Development & Innovation',
    isActive: true,
  },
  {
    id: 'king-3',
    name: 'Daniel Mensah',
    nickname: 'Danny',
    department: 'Electrical Engineering',
    year: 'Level 400',
    category: 'king',
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=500&fit=crop&auto=format',
    bio: 'Community volunteer and sports champion representing MTU at national robotics and athletics competitions.',
    talent: 'Robotics & Community Service',
    isActive: true,
  },
  // Queen
  {
    id: 'queen-1',
    name: 'Abena Owusu',
    nickname: 'Abby',
    department: 'Business Administration',
    year: 'Level 400',
    category: 'queen',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=500&fit=crop&auto=format',
    bio: 'Entrepreneur whose non-profit has empowered 500+ young women in STEM fields across the country.',
    talent: 'Entrepreneurship & Mentorship',
    isActive: true,
  },
  {
    id: 'queen-2',
    name: 'Priscilla Darko',
    nickname: 'Priscy',
    department: 'Computer Science',
    year: 'Level 300',
    category: 'queen',
    photo: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=500&fit=crop&auto=format',
    bio: 'Software engineer intern, campus ambassador, and undefeated debate team captain at MTU for 3 years.',
    talent: 'Technology & Competitive Debate',
    isActive: true,
  },
  {
    id: 'queen-3',
    name: 'Nana Yaa Asante',
    nickname: 'NY',
    department: 'Civil Engineering',
    year: 'Level 400',
    category: 'queen',
    photo: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=500&fit=crop&auto=format',
    bio: 'Research scholar leading the campus sustainability committee — her work reduced MTU energy use by 18%.',
    talent: 'Research & Environmental Advocacy',
    isActive: true,
  },
  {
    id: 'style-1',
    name: 'Honey Nway Oo',
    nickname: 'Honey',
    department: 'Mechatronics Engineering',
    year: 'Level 300',
    category: 'style',
    photo: '/Honey.jpg',
    bio: 'Fashion designer and style blogger whose campus looks go viral on social media every week.',
    talent: 'Fashion Design & Personal Styling',
    isActive: true,
  },
  {
    id: 'style-2',
    name: 'Khin Wint Wah',
    nickname: 'Wint Wah',
    department: 'Electrical Engineering',
    year: 'Level 300',
    category: 'style',
    photo: '/khinwintwah.jpg',
    bio: 'Brand ambassador blending rich African heritage with contemporary street style aesthetics.',
    talent: 'Brand Identity & Cultural Fashion',
    isActive: true,
  },
  {
    id: 'style-3',
    name: 'Wutt Hmone Shwe Yi',
    nickname: 'Kit Kit',
    department: 'Electrical Power Engineering',
    year: 'Level 400',
    category: 'style',
    photo: '/KitKit.jpg',
    bio: 'Architect-in-training whose design sense extends from blueprints to her iconic personal style.',
    talent: 'Aesthetic Design & Visual Art',
    isActive: true,
  },
  {
    id: 'smart-1',
    name: 'Tayza lin Young',
    nickname: 'Tayza',
    department: 'Computer Science and Information Technology',
    year: 'Level 400',
    category: 'smart',
    photo: '/Tazya.jpg',
    bio: 'AI researcher with 3 published papers, perfect CGPA, and winner of the National Science Olympiad.',
    talent: 'Artificial Intelligence & Research',
    isActive: true,
  },
  {
    id: 'smart-2',
    name: 'Nyein Thaw',
    nickname: 'NT',
    department: 'Mechatronics Engineering',
    year: 'Level 300',
    category: 'smart',
    photo: '/nyein.jpg',
    bio: 'Mathematics prodigy who represented Ghana at the International Mathematical Olympiad 2025.',
    talent: 'Pure Mathematics & Problem Solving',
    isActive: true,
  },
  {
    id: 'smart-3',
    name: 'Shein Tin Htoo',
    nickname: 'Shein',
    department: 'Mechanical Engineering',
    year: 'Level 400',
    category: 'smart',
    photo: '/Shein.jpg',
    bio: 'Physics wizard and quiz champion who has won 5 consecutive inter-university quiz competitions.',
    talent: 'Physics & Academic Competition',
    isActive: true,
  },
];


export const ADMIN_EMAIL = 'admin@mtu.edu.mm';
export const ADMIN_PASSWORD = 'MTU2026';

export const INITIAL_ELECTION: ElectionState = {
  id: 'elect-2026',
  name: 'MTU Voting 2026',
  status: 'open',
  opensAt: new Date('2026-07-22T09:00:00'),
  closesAt: new Date('2026-07-27T23:59:59'),
  publishedAt: null,
};

export const INITIAL_VOTES: Record<string, number> = {
  'king-1': 142, 'king-2': 98, 'king-3': 76,
  'queen-1': 167, 'queen-2': 134, 'queen-3': 89,
  'style-1':187, 'style-2':23, 'style-3':45,
  'smart-1':121, 'smart-2':134, 'smart-3':56
};

export const LIVESTREAM_CHAT = [
  { name: 'Aye M.', msg: 'This competition is amazing! 🔥', time: '18:02' },
  { name: 'Ko Ko', msg: 'Emmanuel for King! 👑', time: '18:03' },
  { name: 'Su Su', msg: 'Abena deserves Queen all day!', time: '18:04' },
  { name: 'Admin', msg: '📢 Voting closes July 25 at midnight!', time: '18:05' },
  { name: 'Thurein', msg: 'Best event MTU has done 🙌', time: '18:06' },
  { name: 'Phyu', msg: 'Priscilla is so talented 💪', time: '18:07' },
  { name: 'Zaw', msg: 'MTU representing 🇲🇲', time: '18:08' },
  { name: 'Khin', msg: 'So proud of all candidates!', time: '18:09' },
];
