import type { Candidate,  ElectionState } from './types';

export const CANDIDATES: Candidate[] = [
  // King
    {
    id: 'king-1',
    name: 'Daung',
    nickname: 'Alvin',
    department: 'Mechanical Engineering',
    year: 'First Year',
    category: 'king',
    photo: 'https://i.pinimg.com/originals/cb/70/66/cb7066f2d6117366f7a14bb9f4401202.jpg',
    bio: 'From Meiktila, Studied at BEHS 1 Meiktila, Height:1.8m',
    talent: 'Good at problem solving',
    isActive: true,
  },
  {
    id: 'king-2',
    name: 'Paing Takhon',
    nickname: 'Jack',
    department: 'Architecture',
    year: 'First Year',
    category: 'king',
    photo: 'https://tse2.mm.bing.net/th/id/OIP.Nc-LYkRZ74hlflLK_afaZQHaLd?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
    bio: 'From Kawthoung, Studied at BEHS 1 Khamaukgyi, Height:1.88m',
    talent: 'Presentation skills',
    isActive: true,
  },
  {
    id: 'king-3',
    name: 'Kaung Myat San',
    nickname: 'Harry',
    department: 'Civil Engineering',
    year: 'First Year',
    category: 'king',
    photo: 'https://tse4.mm.bing.net/th/id/OIP.ap7Heh-ngs8oS_UwEzvo1QHaLG?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
    bio: 'From Yangon, Studied at BEHS 2 Dagon, Height: 1.78m',
    talent: 'Robotics & Community Service',
    isActive: true,
  },
  // Queen
  {
    id: 'queen-1',
    name: 'Hsaung Wutyee May',
    nickname: 'Abby',
    department: 'Electronic Engineering',
    year: 'First Year',
    category: 'queen',
    photo: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgtE8-9kMW_XrzDDhXF47ogCJ6r5SAS2A_w094t4gYKV2AKYhichvL5Xa4tESh_in5V8fTF736OvGvlTtcBZYtN1EtLdLsg64JvLfeRfc4RTIaFTt3qKRExCcDser10LHFtcZgl-23hqu2ywAwwB6wUnJm0pJJhQTygR65Lld2kLUpdPvaxWm4XRQ011w/s2048/308462275_654117296072973_1024788347621804352_n.jpg',
    bio: 'From Yangon, Studied at BEHS 2 Bahan, Height: 1.68m',
    talent: 'Teamwork,Leadership',
    isActive: true,
  },
  {
    id: 'queen-2',
    name: 'Poe Mamhe Thar',
    nickname: 'Priscy',
    department: 'Electrical power',
    year: 'First Year',
    category: 'queen',
    photo: 'https://i.pinimg.com/736x/51/6c/1e/516c1e409248036c08dac4602348c2ea.jpg',
    bio: 'From Yangon, Studied at BEHS 2 Bahan, Height: 1.68m',
    talent: 'Leadership and critical thinking under pressure',
    isActive: true,
  },
  {
    id: 'queen-3',
    name: 'May Myint Mo',
    nickname: 'NY',
    department: 'Mechatronic Engineering',
    year: 'First Year',
    category: 'queen',
    photo: 'https://tse4.mm.bing.net/th/id/OIP.7gIP_buX1pMer1afQsMbaAHaLM?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
    bio: 'From Yangon, Studied at BEHS 2 Sanchaung, Height: 1.63m',
    talent: 'Teamwork and computer drafting',
    isActive: true,
  },
  {
    id: 'style-1',
    name: 'Honey Nway Oo',
    nickname: 'Honey',
    department: 'Mechatronics Engineering',
    year: 'First Year',
    category: 'style',
    photo: '/Honey.jpg',
    bio: 'Fashion designer and style blogger whose campus looks go viral on social media every week.',
    talent: 'Fashion Design & Personal Styling',
    isActive: true,
  },
  {
    id: 'style-2',
    name: 'Khin Wint Wah',
    nickname: 'Wint Wah',
    department: 'Electrical Engineering',
    year: 'First Year',
    category: 'style',
    photo: '/khinwintwah.jpg',
    bio: 'Brand ambassador blending rich African heritage with contemporary street style aesthetics.',
    talent: 'Brand Identity & Cultural Fashion',
    isActive: true,
  },
  {
    id: 'style-3',
    name: 'Wutt Hmone Shwe Yi',
    nickname: 'Kit Kit',
    department: 'Electrical Power Engineering',
    year: 'First Year',
    category: 'style',
    photo: '/KitKit.jpg',
    bio: 'Architect-in-training whose design sense extends from blueprints to her iconic personal style.',
    talent: 'Aesthetic Design & Visual Art',
    isActive: true,
  },
  {
    id: 'smart-1',
    name: 'Tayza lin Young',
    nickname: 'Tayza',
    department: 'Computer Science and Information Technology',
    year: 'First Year',
    category: 'smart',
    photo: '/Tazya.jpg',
    bio: 'AI researcher with 3 published papers, perfect CGPA, and winner of the National Science Olympiad.',
    talent: 'Artificial Intelligence & Research',
    isActive: true,
  },
  {
    id: 'smart-2',
    name: 'Nyein Thaw',
    nickname: 'NT',
    department: 'Mechatronics Engineering',
    year: 'First Year',
    category: 'smart',
    photo: '/nyein.jpg',
    bio: 'Mathematics prodigy who represented Ghana at the International Mathematical Olympiad 2025.',
    talent: 'Pure Mathematics & Problem Solving',
    isActive: true,
  },
  {
    id: 'smart-3',
    name: 'Shein Tin Htoo',
    nickname: 'Shein',
    department: 'Mechanical Engineering',
    year: 'First Year',
    category: 'smart',
    photo: '/Shein.jpg',
    bio: 'Physics wizard and quiz champion who has won 5 consecutive inter-university quiz competitions.',
    talent: 'Physics & Academic Competition',
    isActive: true,
  },
];


export const ADMIN_EMAIL = 'admin@mtu.edu.mm';
export const ADMIN_PASSWORD = 'MTUfresher&2026';

export const INITIAL_ELECTION: ElectionState = {
  id: 'elect-2026',
  name: 'MTU Voting 2026',
  status: 'open',
  opensAt: new Date('2026-07-22T09:00:00'),
  closesAt: new Date('2026-07-27T23:59:59'),
  publishedAt: null,
};

export const INITIAL_VOTES: Record<string, number> = {
  'king-1': 142, 'king-2': 98, 'king-3': 76,
  'queen-1': 167, 'queen-2': 134, 'queen-3': 89,
  'style-1':187, 'style-2':23, 'style-3':45,
  'smart-1':121, 'smart-2':134, 'smart-3':56
};

export const LIVESTREAM_CHAT = [
  { name: 'Aye M.', msg: 'This competition is amazing! 🔥', time: '18:02' },
  { name: 'Ko Ko', msg: 'Emmanuel for King! 👑', time: '18:03' },
  { name: 'Su Su', msg: 'Abena deserves Queen all day!', time: '18:04' },
  { name: 'Admin', msg: '📢 Voting closes July 25 at midnight!', time: '18:05' },
  { name: 'Thurein', msg: 'Best event MTU has done 🙌', time: '18:06' },
  { name: 'Phyu', msg: 'Priscilla is so talented 💪', time: '18:07' },
  { name: 'Zaw', msg: 'MTU representing 🇲🇲', time: '18:08' },
  { name: 'Khin', msg: 'So proud of all candidates!', time: '18:09' },
];
