import type { Candidate,  ElectionState } from './types';

export const CANDIDATES: Candidate[] = [
  // King
    {
    id: 'king-1',
    name: 'Daung',
    nickname: 'Alvin',
    department: 'Mechanical Engineering',
    year: 'First Year',
    category: 'king',
    photo: 'https://i.pinimg.com/originals/cb/70/66/cb7066f2d6117366f7a14bb9f4401202.jpg',
    bio: 'From Meiktila, Studied at BEHS 1 Meiktila, Height:1.8m',
    talent: 'Good at problem solving',
    isActive: true,
  },
  {
    id: 'king-2',
    name: 'Paing Takhon',
    nickname: 'Jack',
    department: 'Architecture',
    year: 'First Year',
    category: 'king',
    photo: 'https://share.google/O9cej68aXhKBnJinw',
    bio: 'From Kawthoung, Studied at BEHS 1 Khamaukgyi, Height:1.88m',
    talent: 'Presentation skills',
    isActive: true,
  },
  {
    id: 'king-3',
    name: 'Kaung Myat San',
    nickname: 'Harry',
    department: 'Civil Engineering',
    year: 'First Year',
    category: 'king',
    photo: 'https://www.bing.com/images/search?view=detailV2&ccid=ap7Heh%2bn&id=6560A567FA17419847A87C82B0C0690A37F055CD&thid=OIP.ap7Heh-ngs8oS_UwEzvo1QHaLG&mediaurl=https%3a%2f%2flookaside.fbsbx.com%2flookaside%2fcrawler%2fmedia%2f%3fmedia_id%3d1467720281383532&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.6a9ec77a1fa782cf284bf530133be8d5%3frik%3dzVXwNwppwLCCfA%26pid%3dImgRaw%26r%3d0&exph=2048&expw=1366&q=kaung+myat+san&FORM=IRPRST&ck=C68A3B18D2C3DE341DCFF7EF0AD22669&selectedIndex=67&itb=0',
    bio: 'From Yangon, Studied at BEHS 2 Dagon, Height: 1.78m',
    talent: 'Robotics & Community Service',
    isActive: true,
  },
  // Queen
  {
    id: 'queen-1',
    name: 'Hsaung Wutyee May',
    nickname: 'Abby',
    department: 'Electronic Engineering',
    year: 'First Year',
    category: 'queen',
    photo: 'https://www.bing.com/images/search?view=detailV2&ccid=l3C60Opq&id=977A32B170CAD43D845A78289E32A48BDC065B27&thid=OIP.l3C60OpqQl7vsoT9BrvnaQHaHa&mediaurl=https%3a%2f%2fyt3.googleusercontent.com%2fPvaCUgkVbRh4VAwKYCWHqK9wJpoY2TtW80i55l7q2Re1tRMsTzcV88ZYuAI6RDrfsMkPldDAcA%3ds900-c-k-c0x00ffffff-no-rj&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.9770bad0ea6a425eefb284fd06bbe769%3frik%3dJ1sG3IukMp4oeA%26pid%3dImgRaw%26r%3d0&exph=900&expw=900&q=hsaung+wutyee+may&FORM=IRPRST&ck=2125DF8AFA9BEC9B2B020E783B31F6AF&selectedIndex=28&itb=0',
    bio: 'From Yangon, Studied at BEHS 2 Bahan, Height: 1.68m',
    talent: 'Teamwork,Leadership',
    isActive: true,
  },
  {
    id: 'queen-2',
    name: 'Poe Mamhe Thar',
    nickname: 'Priscy',
    department: 'Electrical power',
    year: 'First Year',
    category: 'queen',
    photo: 'https://i.pinimg.com/736x/51/6c/1e/516c1e409248036c08dac4602348c2ea.jpg',
    bio: 'From Yangon, Studied at BEHS 2 Bahan, Height: 1.68m',
    talent: 'Leadership and critical thinking under pressure',
    isActive: true,
  },
  {
    id: 'queen-3',
    name: 'May Myint Mo',
    nickname: 'NY',
    department: 'Mechatronic Engineering',
    year: 'First Year',
    category: 'queen',
    photo: 'https://tse4.mm.bing.net/th/id/OIP.7gIP_buX1pMer1afQsMbaAHaLM?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
    bio: 'From Yangon, Studied at BEHS 2 Sanchaung, Height: 1.63m',
    talent: 'Teamwork and computer drafting',
    isActive: true,
  },
  {
    id: 'style-1',
    name: 'Honey Nway Oo',
    nickname: 'Honey',
    department: 'Mechatronics Engineering',
    year: 'Level 300',
    category: 'style',
    photo: '/Honey.jpg',
    bio: 'Fashion designer and style blogger whose campus looks go viral on social media every week.',
    talent: 'Fashion Design & Personal Styling',
    isActive: true,
  },
  {
    id: 'style-2',
    name: 'Khin Wint Wah',
    nickname: 'Wint Wah',
    department: 'Electrical Engineering',
    year: 'Level 300',
    category: 'style',
    photo: '/khinwintwah.jpg',
    bio: 'Brand ambassador blending rich African heritage with contemporary street style aesthetics.',
    talent: 'Brand Identity & Cultural Fashion',
    isActive: true,
  },
  {
    id: 'style-3',
    name: 'Wutt Hmone Shwe Yi',
    nickname: 'Kit Kit',
    department: 'Electrical Power Engineering',
    year: 'Level 400',
    category: 'style',
    photo: '/KitKit.jpg',
    bio: 'Architect-in-training whose design sense extends from blueprints to her iconic personal style.',
    talent: 'Aesthetic Design & Visual Art',
    isActive: true,
  },
  {
    id: 'smart-1',
    name: 'Tayza lin Young',
    nickname: 'Tayza',
    department: 'Computer Science and Information Technology',
    year: 'Level 400',
    category: 'smart',
    photo: '/Tazya.jpg',
    bio: 'AI researcher with 3 published papers, perfect CGPA, and winner of the National Science Olympiad.',
    talent: 'Artificial Intelligence & Research',
    isActive: true,
  },
  {
    id: 'smart-2',
    name: 'Nyein Thaw',
    nickname: 'NT',
    department: 'Mechatronics Engineering',
    year: 'Level 300',
    category: 'smart',
    photo: '/nyein.jpg',
    bio: 'Mathematics prodigy who represented Ghana at the International Mathematical Olympiad 2025.',
    talent: 'Pure Mathematics & Problem Solving',
    isActive: true,
  },
  {
    id: 'smart-3',
    name: 'Shein Tin Htoo',
    nickname: 'Shein',
    department: 'Mechanical Engineering',
    year: 'Level 400',
    category: 'smart',
    photo: '/Shein.jpg',
    bio: 'Physics wizard and quiz champion who has won 5 consecutive inter-university quiz competitions.',
    talent: 'Physics & Academic Competition',
    isActive: true,
  },
];


export const ADMIN_EMAIL = 'admin@mtu.edu.mm';
export const ADMIN_PASSWORD = 'MTU2026';

export const INITIAL_ELECTION: ElectionState = {
  id: 'elect-2026',
  name: 'MTU Voting 2026',
  status: 'open',
  opensAt: new Date('2026-07-22T09:00:00'),
  closesAt: new Date('2026-07-27T23:59:59'),
  publishedAt: null,
};

export const INITIAL_VOTES: Record<string, number> = {
  'king-1': 142, 'king-2': 98, 'king-3': 76,
  'queen-1': 167, 'queen-2': 134, 'queen-3': 89,
  'style-1':187, 'style-2':23, 'style-3':45,
  'smart-1':121, 'smart-2':134, 'smart-3':56
};

export const LIVESTREAM_CHAT = [
  { name: 'Aye M.', msg: 'This competition is amazing! 🔥', time: '18:02' },
  { name: 'Ko Ko', msg: 'Emmanuel for King! 👑', time: '18:03' },
  { name: 'Su Su', msg: 'Abena deserves Queen all day!', time: '18:04' },
  { name: 'Admin', msg: '📢 Voting closes July 25 at midnight!', time: '18:05' },
  { name: 'Thurein', msg: 'Best event MTU has done 🙌', time: '18:06' },
  { name: 'Phyu', msg: 'Priscilla is so talented 💪', time: '18:07' },
  { name: 'Zaw', msg: 'MTU representing 🇲🇲', time: '18:08' },
  { name: 'Khin', msg: 'So proud of all candidates!', time: '18:09' },
];
